#!/bin/sh

if [ -z $SERVALINSTANCE_PATH ]; then
	echo No SERVALINSTANCE_PATH set!!
	export SERVALINSTANCE_PATH=/tmp/serval	
#exit 1
fi

if [ -z $1 ]; then
	echo "Usage $0 <folder>"
	exit 1
fi

SID=`$SERVAL_ROOT/servald id self | sed -n 3p`

for f in $1; do
	$SERVAL_ROOT/servald rhizome add file $SID $1
done
