#!/bin/sh

if [ -z $SERVALINSTANCE_PATH ]; then
	echo No SERVALINSTANCE_PATH set!!
	exit 1
fi

if [ -z $1 ]; then
	echo "Usage $0 <folder>"
	exit 1
fi

SID=`./servald id self | sed -n 3p`

tar -zcvf /tmp/`basename $1`.tar.gz $1

./servald rhizome add file $SID /tmp/`basename $1`.tar.gz

rm /tmp/`basename $1`.tar.gz

